<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $now  = now();
        $categories = Category::query()->get()->pluck('id', 'name');

        $jsonConvert = fn($v) => $v === null ? null : json_encode($v, JSON_UNESCAPED_UNICODE);

        $products = [
            [
                'category_id' => $categories['Smartphones'],
                'name' => 'Apple iPhone 15 (128 GB)',
                'image' => 'https://m.media-amazon.com/images/I/612mSuve9bL._AC_SX679_.jpg',
                'price' => 859.00,
                'rating' => 4.4,
                'key_features' => $jsonConvert(['6.1" OLED (Super Retina XDR)', '48 MP main camera', 'USB-C', 'A16 Bionic', 'Dynamic Island']),
                'pros' => $jsonConvert(['Reliable camera for everyday photos', 'USB-C instead of Lightning']),
                'cons' => $jsonConvert(['60 Hz display', 'No telephoto lens']),
                'trending_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Smartphones'],
                'name' => 'Google Pixel 8a (128 GB)',
                'image' => 'https://m.media-amazon.com/images/I/61lGgRpIsXL._AC_SX679_.jpg',
                'price' => 449.00,
                'rating' => 4.5,
                'key_features' => $jsonConvert(['6.1" OLED 120 Hz', 'Tensor G3', '7 years of updates', '64 MP main camera']),
                'pros' => null,
                'cons' => null,
                'trending_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Smartphones'],
                'name' => 'Samsung Galaxy S24 (128 GB)',
                'image' => 'https://m.media-amazon.com/images/I/61uakkLoHxL._AC_UY436_QL65_.jpg',
                'price' => 439.00,
                'rating' => null,
                'key_features' => $jsonConvert(['6.2" AMOLED', 'Galaxy AI features', 'IP68']),
                'pros' => $jsonConvert(['Very bright display', 'Long software support']),
                'cons' => $jsonConvert(['AI features not always useful', 'Some markets use Exynos']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Smartphones'],
                'name' => 'Xiaomi Redmi Note 13 Pro 5G (8/128)',
                'image' => 'https://m.media-amazon.com/images/I/71jok2WwLFL._AC_UY436_QL65_.jpg',
                'price' => 328.00,
                'rating' => null,
                'key_features' => null,
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Smartphones'],
                'name' => 'OnePlus 13 (12/256)',
                'image' => 'https://m.media-amazon.com/images/I/71gXK0cwIjL._AC_UY436_QL65_.jpg',
                'price' => 879.00,
                'rating' => 4.6,
                'key_features' => $jsonConvert(['6.8" OLED QHD+', 'Snapdragon 8 Elite', 'IP69']),
                'pros' => $jsonConvert(['Very fast interface', 'Long battery life']),
                'cons' => $jsonConvert(['Fewer AI features than competitors']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Laptops'],
                'name' => 'Apple MacBook Air 13 (M3, 2024)',
                'image' => 'https://m.media-amazon.com/images/I/71x9JI-Il0L._AC_UY436_QL65_.jpg',
                'price' => 1249.00,
                'rating' => 4.7,
                'key_features' => $jsonConvert(['Chip M3', '13.6" Liquid Retina', 'fanless design', 'two external monitors with lid closed']),
                'pros' => $jsonConvert(['Silent and cool', 'Long battery life']),
                'cons' => $jsonConvert(['Relatively few ports']),
                'trending_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Laptops'],
                'name' => 'Dell XPS 13',
                'image' => 'https://m.media-amazon.com/images/I/71mjHAu18nL._AC_UY436_QL65_.jpg',
                'price' => 1349.00,
                'rating' => 4.5,
                'key_features' => $jsonConvert(['13" 16:10 display', 'aluminum body', 'Thunderbolt 4']),
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Laptops'],
                'name' => 'Lenovo IdeaPad 5 (14")',
                'image' => 'https://m.media-amazon.com/images/I/715gt85hlVL._AC_UY436_QL65_.jpg',
                'price' => 729.00,
                'rating' => null,
                'key_features' => $jsonConvert(['14" IPS', 'Ryzen or Intel Core', 'lightweight chassis']),
                'pros' => $jsonConvert(['Good price-to-performance ratio']),
                'cons' => $jsonConvert(['Average speakers']),
                'trending_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Laptops'],
                'name' => 'HP 15 (series 15-da1xxx)',
                'image' => 'https://m.media-amazon.com/images/I/71l1ZQNil4L._AC_UY436_QL65_.jpg',
                'price' => 499.00,
                'rating' => null,
                'key_features' => null,
                'pros' => null,
                'cons' => null,
                'trending_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Laptops'],
                'name' => 'ASUS Zenbook 14 OLED (UX5406)',
                'image' => 'https://m.media-amazon.com/images/I/71FB35uifML._AC_UY436_QL65_.jpg',
                'price' => 1299.00,
                'rating' => 4.6,
                'key_features' => $jsonConvert(['14" OLED', 'thin/light', 'Intel Core Ultra']),
                'pros' => $jsonConvert(['Excellent display quality', 'Portability']),
                'cons' => $jsonConvert(['Expensive in top configurations']),
                'trending_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Earbuds'],
                'name' => 'Apple AirPods Pro (2nd gen, USB-C)',
                'image' => 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UY436_QL65_.jpg',
                'price' => 189.00,
                'rating' => 4.6,
                'key_features' => $jsonConvert(['ANC', 'Transparency', 'USB-C case']),
                'pros' => $jsonConvert(['Excellent Transparency mode', 'Apple ecosystem']),
                'cons' => $jsonConvert(['Better for iOS than Android']),
                'trending_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Earbuds'],
                'name' => 'Sony WF-1000XM5',
                'image' => 'https://m.media-amazon.com/images/I/61qmsGnacvL._AC_UY436_QL65_.jpg',
                'price' => 299.90,
                'rating' => 4.7,
                'key_features' => $jsonConvert(['Flagship-level ANC', 'LE Audio / Auracast (via update)']),
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Earbuds'],
                'name' => 'Bose QuietComfort Ultra Earbuds',
                'image' => 'https://m.media-amazon.com/images/I/71M-El1aDtL._AC_UY436_QL65_.jpg',
                'price' => 349.95,
                'rating' => null,
                'key_features' => $jsonConvert(['Immersive Audio', 'ANC']),
                'pros' => $jsonConvert(['Comfortable fit', 'Stable ANC']),
                'cons' => $jsonConvert(['High price']),
                'trending_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Earbuds'],
                'name' => 'Samsung Galaxy Buds2 Pro',
                'image' => 'https://m.media-amazon.com/images/I/61efn6CoyOL._AC_UY436_QL65_.jpg',
                'price' => 169.00,
                'rating' => null,
                'key_features' => null,
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Earbuds'],
                'name' => 'Jabra Elite 8 Active',
                'image' => 'https://m.media-amazon.com/images/I/61oxsNpsVWL._AC_UY436_QL65_.jpg',
                'price' => 219.00,
                'rating' => 4.4,
                'key_features' => $jsonConvert(['IP68', 'ANC', 'Sports profile']),
                'pros' => $jsonConvert(['Very durable', 'Secure fit']),
                'cons' => $jsonConvert(['Sound is less "audiophile" than Sony/Bose']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Robot Vacuums'],
                'name' => 'iRobot Roomba j7',
                'image' => 'https://m.media-amazon.com/images/I/71M6KSexe5L._AC_UY436_QL65_.jpg',
                'price' => 395.18,
                'rating' => 4.4,
                'key_features' => $jsonConvert(['PrecisionVision navigation', 'Avoids cables', 'App control']),
                'pros' => $jsonConvert(['Avoids obstacles well', 'Convenient app']),
                'cons' => $jsonConvert(['Dock can be noisy (on auto-empty versions)']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Robot Vacuums'],
                'name' => 'Roborock S8',
                'image' => 'https://m.media-amazon.com/images/I/61nkKvzm+1L._AC_UY436_QL65_.jpg',
                'price' => 502.95,
                'rating' => 4.6,
                'key_features' => $jsonConvert(['6000 Pa suction', 'dual rubber brushes', 'LiDAR']),
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Robot Vacuums'],
                'name' => 'ECOVACS Deebot T20 Omni',
                'image' => 'https://m.media-amazon.com/images/I/71x23lgsF6L._AC_UY436_QL65_.jpg',
                'price' => 659.68,
                'rating' => null,
                'key_features' => $jsonConvert(['Hot mop washing ~55°C', 'Auto mop lift on carpets', '3D obstacle avoidance']),
                'pros' => $jsonConvert(['All-in-one dock', 'Strong mopping']),
                'cons' => $jsonConvert(['Bulky base']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Robot Vacuums'],
                'name' => 'Dreame L10s Ultra Gen 2',
                'image' => 'https://m.media-amazon.com/images/I/61rV0WmplkL._AC_UY436_QL65_.jpg',
                'price' => 444.00,
                'rating' => null,
                'key_features' => null,
                'pros' => null,
                'cons' => null,
                'trending_order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Robot Vacuums'],
                'name' => 'Xiaomi Robot Vacuum S10',
                'image' => 'https://m.media-amazon.com/images/I/61T3QADwWuL._AC_UY436_QL65_.jpg',
                'price' => 169.90,
                'rating' => 4.3,
                'key_features' => $jsonConvert(['4000 Pa', 'LDS navigation', 'up to 130 min']),
                'pros' => $jsonConvert(['Great price']),
                'cons' => $jsonConvert(['Small dustbin']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Security Cameras'],
                'name' => 'Google Nest Cam (battery)',
                'image' => 'https://m.media-amazon.com/images/I/31750hI5MLL._AC_UY436_QL65_.jpg',
                'price' => 199.99,
                'rating' => 4.5,
                'key_features' => $jsonConvert(['Wireless', 'Full HD', 'Event recognition in Google Home']),
                'pros' => $jsonConvert(['Easy installation', 'Works in Google ecosystem']),
                'cons' => $jsonConvert(['Additional features require subscription']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Security Cameras'],
                'name' => 'Arlo Pro 5 (2K)',
                'image' => 'https://m.media-amazon.com/images/I/61od55N7+jL._AC_UY436_QL65_.jpg',
                'price' => 259.00,
                'rating' => 4.4,
                'key_features' => $jsonConvert(['2K HDR', 'Color night vision', 'Works over Wi-Fi']),
                'pros' => null,
                'cons' => null,
                'trending_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Security Cameras'],
                'name' => 'Eufy SoloCam S340 (3K, Solar)',
                'image' => 'https://m.media-amazon.com/images/I/61s8F2bs-FL._AC_UY436_QL65_.jpg',
                'price' => 129.99,
                'rating' => null,
                'key_features' => $jsonConvert(['3K, 8× zoom', 'Solar panel', '360° pan/tilt']),
                'pros' => $jsonConvert(['No subscription', 'Solar power']),
                'cons' => $jsonConvert(['Needs good sunlight for solar charging']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Security Cameras'],
                'name' => 'Ring Stick Up Cam Battery',
                'image' => 'https://m.media-amazon.com/images/I/31VRe0K1GSL._AC_UY436_QL65_.jpg',
                'price' => 99.99,
                'rating' => null,
                'key_features' => null,
                'pros' => null,
                'cons' => null,
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Security Cameras'],
                'name' => 'TP-Link Tapo C320WS (2K, Outdoor)',
                'image' => 'https://m.media-amazon.com/images/I/61rxbOGRZDL._AC_UY436_QL65_.jpg',
                'price' => 44.99,
                'rating' => 4.5,
                'key_features' => $jsonConvert(['2K QHD 4MP', 'Color night vision (Starlight)', 'IP66']),
                'pros' => $jsonConvert(['Very cheap for 2K', 'Good night image quality']),
                'cons' => $jsonConvert(['No battery (wired power)']),
                'trending_order' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('products')->insertOrIgnore($products);
    }
}
